### ISSUE TITLE
Crashes when user joins the server

### ISSUE THREAD

**Issue by crazybrain23** [WillShaw1100/BiscuitBot#31]
Automattic/node-canvas#1709 might be releated.
Error message
```
Error: Unsupported image type
     at setSource (/home/will/BiscuitBot/node_modules/canvas/lib/image.js:91:13)
     at /home/will/BiscuitBot/node_modules/canvas/lib/image.js:59:11
     at /home/will/BiscuitBot/node_modules/simple-get/index.js:97:7
     at IncomingMessage.<anonymous> (/home/will/BiscuitBot/node_modules/simple-concat/index.js:8:13)
     at Object.onceWrapper (node:events:627:28)
     at IncomingMessage.emit (node:events:525:35)
     at endReadableNT (node:internal/streams/readable:1358:12)
     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
Update: it only crashes when the joining member has an avatar.

**Comment by crazybrain23** [comment]
It seems to also be affected by /slap
